services:
  lightrag:
    container_name: lightrag
    image: ghcr.io/hkuds/lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/hkuds/lightrag:latest
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./data/rag_storage:/data/claraly-rag/data/rag_storage
      - ./data/inputs:/data/claraly-rag/data/inputs
      - ./data/tiktoken:/data/claraly-rag/data/tiktoken
      - ./config.ini:/data/claraly-rag/config.ini
      - ./.env:/data/claraly-rag/.env
    env_file:
      - .env
    environment:
      - TIKTOKEN_CACHE_DIR=/data/claraly-rag/data/tiktoken
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
